### ISSUE TITLE
Sails E_VALIDATION Error

### ISSUE THREAD

**Issue by tonespy** [agenthunt/waterline-to-graphql#2]
I am trying to use the module but, haven't been able to utilize it.

I did the normal `Sails Model/Controller` configuration. But, anytime I try to use the endpoint, I get an `E_VALIDATION Error`.

**DownloadController.js**

	module.exports = {

		downloadGraphql: (req, res) => {

			const data = req.body;
			let schema = graphWaterline.getGraphQLSchemaFrom(sails.models);
			graphql.graphql(schema, data.query, null).then(result => {
				console.log(JSON.stringify(result, null, 2));
			}).catch(err => console.log("OfficialError: ", err));
		}
	};

**Testing With Mocha**
**DownloadController.test.js**

	describe("UserController Tests", () => {

		before(done => {
			done();
		})

		describe("#create", () => {

			it("should return 200: Download Created successfully", done => {
		        request(sails.hooks.http.app)
		            .post('/download')
		            .expect(200)
		            .send({"query": `mutation download{createDownload(name:"The Sone", magnetUrl:"ssasasuadiuisudis", totalSize:"200MB", stillInDirectory:true){id, name, magnetUrl, stillInDirectory}}`})
		            .end((err, res) => {
		                /*if (err) console.log("ResponseError: ", err.body);
						console.log("ResponseBody: ", res.body);*/
		                done();
		            });
		    });
		})
	})

When I run `mocha` to test, I added a before validate in my model, and I get this:

	ModelLog:  { 
		isCompleted: false,
		stillInDirectory: false,
		isDownloading: false 
	}

And this is the full error:

	{
	  "data": {
	    "createDownload": null
	  },
	  "errors": [
	    {
	      "message": "[Error (E_VALIDATION) 2 attributes are invalid] Invalid attributes sent to Download:\n • name\n   • Value should be a string (instead of null, which is an object)\n   • \"required\" validation rule failed for input: null\nSpecifically, it threw an error.  Details:\n undefined\n • magnetUrl\n   • Value should be a string (instead of null, which is an object)\n   • \"required\" validation rule failed for input: null\nSpecifically, it threw an error.  Details:\n undefined\n",
	      "locations": [
	        {
	          "line": 1,
	          "column": 19
	        }
	      ],
	      "path": [
	        "createDownload"
	      ]
	    }
	  ]
	}

This is my full model:

	module.exports = {

		attributes: {

			name: {
				type: 'string',
				required: true
			},

			magnetUrl: {
				type: 'string',
				required: true,
			},

			totalSize: {
				type: 'string'
			},

			currentlyDownloaded: {
				type: 'string'
			},

			user: {
				model: 'user'
			},

			isCompleted: {
				type: 'boolean',
				defaultsTo: false
			},

			stillInDirectory: {
				type: 'boolean',
				defaultsTo: false
			},

			isDownloading: {
				type: 'boolean',
				defaultsTo: false
			}
		},

		beforeValidate: function(values, next) {
			console.log("ModelLog: ", values);
			next()
		},

	    softDelete: function(criteria) {
	        return this.update(criteria, {
	            isDeleted: true
	        });
	    }
	};

**Comment by agenthunt** [comment]
Hi, Sorry . Havent been active on this project.  From what I can understand, you are trying to use mutations ?
Mutations are not supported by this module

**Comment by pakTech786** [comment]
@agenthunt  I can't understand how mutations are not supported as i can see their definition <a href="https://github.com/agenthunt/waterline-to-graphql/blob/master/src/getGraphQLSchemaFrom.js">Here</a> at the time of schema generation.

And also 

      let schema = getGraphQLSchemaFrom(models);
      console.log(schema._mutationType);
This gives me following output.
![capture](https://user-images.githubusercontent.com/8026795/27171596-ed3bec08-5166-11e7-9f62-fc9f39b3b9ab.PNG)

**Comment by agenthunt** [comment]
Hi @nailaandleeb , You are right. Basic mutations are supported. It is associations which are not supported. It has been a while I have looked into this repo. Thanks.

@tonespy , I see that the error was due to graphql resolve function argument changes in the latest versions. Have fixed the error and published at 0.0.3 version. Try it out. Hopefully it fixes the issue.

**Comment by pakTech786** [comment]
Yes i replaced that resolver with custom code and it solved the error of deffered promise.
